--- #YAML:1.0
name: MasonX-WebApp
version: 0.05
author:
  - Dave Rolsky, <autarch@urth.org>
abstract: |-
  Works with Mason to do processing before Mason is invoked
license: perl
requires:
  Apache::Session::Wrapper: 0.17
  Class::Data::Inheritable: 0
  Class::Factory::Util: 0
  Exception::Class: 0
  HTML::Mason: 1.1
  URI: 0
provides:
  MasonX::WebApp:
    file: lib/MasonX/WebApp.pm
    version: 0.05
  MasonX::WebApp::ApacheHandler:
    file: lib/MasonX/WebApp.pm
    version: 0.05
generated_by: Module::Build version 0.25
